apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-management-frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-management-frontend
  template:
    metadata:
      labels:
        app: image-management-frontend
    spec:
      containers:
        - name: image-management-frontend
          image: bluestorm1288/iman-front:latest
          volumeMounts:
            - name: upload-storage
              mountPath: /app/public/uploads
      volumes:
        - name: upload-storage
          persistentVolumeClaim:
            claimName: upload-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-management-frontend-srv
spec:
  selector:
    app: image-management-frontend
  ports:
    - name: image-management-frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: image-management-frontend-nodeport
spec:
  type: NodePort
  selector:
    app: image-management-frontend
  ports:
    - name: image-management-frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
