apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.34.0
          ports:
            - containerPort: 5775 # Agent
            - containerPort: 6831 # Thrift compact protocol (UDP)
            - containerPort: 6832 # Thrift binary protocol (UDP)
            - containerPort: 5778 # Agent HTTP
            - containerPort: 16686 # Jaeger Query UI
            - containerPort: 14250 # gRPC (for sending traces)
            - containerPort: 14268 # HTTP endpoint for trace ingestion
            - containerPort: 9411 # Zipkin API (if Zipkin support is enabled)
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_HTTP_PORT
              value: '9411'
            - name: JAEGER_AGENT_PORT
              value: '5775' # Correct the port to only the number (no 'tcp://')

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
    - name: query
      port: 16686
      targetPort: 16686
    - name: zipkin
      port: 9411
      targetPort: 9411
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  labels:
    app: jaeger
spec:
  ports:
    - name: agent
      port: 5775
      targetPort: 5775
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
    - name: collector
      port: 14268
      targetPort: 14268
    - name: grpc
      port: 14250
      targetPort: 14250
  selector:
    app: jaeger
