apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-pvc
  namespace: default # Ensure the PVC is created in the correct namespace
spec:
  accessModes:
    - ReadWriteOnce # The PVC will be mounted by only one node at a time (common for single-instance databases)
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-retain
