name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t bluestorm1288/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push bluestorm1288/auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save digital-ocean-ticketing
      - name: Check if deployment exists
        id: check_deployment
        run: |
          if kubectl get deployment auth-depl &>/dev/null; then
            echo "::set-output name=deployment_exists::true"
          else
            echo "::set-output name=deployment_exists::false"
          fi
      - name: Create deployment if it doesn't exist
        if: steps.check_deployment.outputs.deployment_exists == 'false'
        run: kubectl create deployment auth-depl --image=bluestorm1288/auth
      - name: Restart deployment
        if: steps.check_deployment.outputs.deployment_exists == 'false'
        run: kubectl rollout restart deployment auth-depl
